# .nixpacks/nixpacks.toml

[phases.setup]
nixPkgs = [
  "nodejs_18", # ou a versão do Node.js que você está usando (e.g., nodejs_20)
  "openssl",
  "pkg-config", # Adicionado, é frequentemente uma dependência para certos módulos nativos Node.js
  "libuuid", # Pode ser necessário para algumas libs (como pg, dependendo da configuração)
  "postgresql", # Se você precisar de ferramentas PostgreSQL no build (ex: pg_dump)
]

[phases.build]
cmds = [
  "npm install",
  "npm run build",
]

[phases.start]
cmd = "npm start"